name: Build
on:
  push:
    branches:
      - "*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node 17
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@coderatparadise'
          cache: 'yarn'
      - name: Setup Auth info
        run: |
            yarn config set npmScopes.coderatparadise.npmAuthToken $NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: yarn
      - run: yarn lint
      - run: yarn build